name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest
      run: |
        export PYTHONPATH=.
        pytest test_main.py -v

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-ci-cd-demo .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/flask-ci-cd-demo
    - name: 🚀 Deploy to Production Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USER }}
        key: ${{ secrets.PROD_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/flask-ci-cd-demo
          
          docker stop flask-app || true
          docker rm flask-app || true

          docker run -d \
            --name flask-app \
            -p 4567:4567 \
            ${{ secrets.DOCKER_USERNAME }}/flask-ci-cd-demo
